#!/usr/bin/env bash
# Configures IP resolution for localhost and facebook.com in /etc/hosts

hosts_content=$(cat /etc/hosts)
hosts_content="${hosts_content//127.0.0.1/127.0.0.2}"

if grep -q "facebook.com" /etc/hosts; then
    hosts_content=$(sed 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts)
    hosts_content="${hosts_content//127.0.0.1/127.0.0.2}"
else
    hosts_content=$(printf "%s\n8.8.8.8 facebook.com" "$hosts_content")
fi

printf "%s\n" "$hosts_content" > /etc/hosts
