#!/usr/bin/env bash
# Configures IP resolution for localhost and facebook.com in /etc/hosts

hosts_content=$(sed 's/127\.0\.0\.1[[:space:]]*localhost/127.0.0.2 localhost/g' /etc/hosts)

if grep -q "facebook.com" /etc/hosts; then
    hosts_content=$(sed 's/.*facebook.com.*/8.8.8.8 facebook.com/' <<< "$hosts_content")
else
    hosts_content=$(printf "%s\n8.8.8.8 facebook.com" "$hosts_content")
fi

printf "%s\n" "$hosts_content" > /etc/hosts
